### ISSUE TITLE
Crash when open inventory in creative mode

### ISSUE THREAD

**Issue by mlus-asuka** [SoyTutta/MyNethersDelight#27]
version:1.20.1-0.1.7

Time: 2024-07-13 15:17:11
Description: Unexpected error

net.minecraftforge.fml.ModLoadingException: My Nether's Delight（mynethersdelight )
§7java.lang.NullPointerException: Registry Object not present: mynethersdelight:hot_wings_bucket
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:118) ~[javafmllanguage-1.20.1-47.2.20.jar%23526!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.20.jar%23525!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.2.20.jar%23525!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.20.jar%23525!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onCreativeModeTabBuildContents(ForgeHooks.java:1633) ~[forge-1.20.1-47.2.20-universal.jar%23529!/:?] {re:classloading}
	at net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23524!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:CreativeModeTabMixin,pl:mixin:A}
	at net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696) ~[client-1.20.1-20230612.114412-srg.jar%23524!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:AccessorCreativeModeTabs,pl:mixin:APP:copycats-common.mixins.json:feature_toggle.CreativeModeTabsAccessor,pl:mixin:APP:quark.mixins.json:CreativeModeTabsMixin,pl:mixin:A}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695) ~[client-1.20.1-20230612.114412-srg.jar%23524!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:AccessorCreativeModeTabs,pl:mixin:APP:copycats-common.mixins.json:feature_toggle.CreativeModeTabsAccessor,pl:mixin:APP:quark.mixins.json:CreativeModeTabsMixin,pl:mixin:A}
	at net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710) ~[client-1.20.1-20230612.114412-srg.jar%23524!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:AccessorCreativeModeTabs,pl:mixin:APP:copycats-common.mixins.json:feature_toggle.CreativeModeTabsAccessor,pl:mixin:APP:quark.mixins.json:CreativeModeTabsMixin,pl:mixin:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.<init>(CreativeModeInventoryScreen.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23524!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:extrasounds.mixins.json:inventory.CreativeInventoryScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_7856_(InventoryScreen.java:48) ~[client-1.20.1-20230612.114412-srg.jar%23524!/:?]

**Comment by mlus-asuka** [comment]
downloaded the 1.7.3 titled one in modrinth but actually is 0.1.7

**Comment by mlus-asuka** [comment]
Never mind, I installed the old version in server because the wrong version in filename.
